// <auto-generated />
using ECommerse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerse.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20180713233258_newSeed")]
    partial class newSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerse.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Sku");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ID = 1, Description = "King of the Dinos", Image = "\\Images\\Tyrannosaurus.jpg", Name = "Tyranosaurus", Price = 199.99m, Sku = "00001" },
                        new { ID = 2, Description = "3 times the power of a Rhinocerous", Image = "https://upload.wikimedia.org/wikipedia/commons/4/4d/Knight_Triceratops.jpg", Name = "Triceratops", Price = 199.99m, Sku = "00002" },
                        new { ID = 3, Description = "Soaring the skies", Image = "http://images.dinosaurpictures.org/pterodactyl-adrian-chesterman_54f6.jpg", Name = "Pteradactyl", Price = 199.99m, Sku = "00003" },
                        new { ID = 4, Description = "Grandpa of the giraffe", Image = "https://en.wikipedia.org/wiki/Brachiosaurus#/media/File:Brachiosaurus_NT_new.jpg", Name = "Brachiosaurus", Price = 199.99m, Sku = "00004" },
                        new { ID = 5, Description = "The walking tank of the Cretaceous", Image = "https://vignette.wikia.nocookie.net/ark-survival-evolved/images/0/07/Ankylosaurus-2.png/revision/latest?cb=20150620091126&path-prefix=fr", Name = "Ankylosaurus", Price = 199.99m, Sku = "00005" },
                        new { ID = 6, Description = "Pack hunting terror of the Creatceous", Image = "https://vignette.wikia.nocookie.net/jurassicpark/images/1/12/Velociraptor-detail-header.png/revision/latest?cb=20150420213742", Name = "Velociraptor", Price = 199.99m, Sku = "00006" },
                        new { ID = 7, Description = "The missing link", Image = "https://en.wikipedia.org/wiki/Archaeopteryx#/media/File:Archaeopteryx_lithographica_by_durbed.jpg", Name = "Archeopteryx", Price = 199.99m, Sku = "00007" },
                        new { ID = 8, Description = "Jurassic terror", Image = "https://upload.wikimedia.org/wikipedia/commons/d/d2/Allosaurus4.jpg", Name = "Allosaurus", Price = 199.99m, Sku = "00008" },
                        new { ID = 9, Description = "The two legged herbivore with a powerful headbutt", Image = "https://en.wikipedia.org/wiki/Pachycephalosaurus#/media/File:Pachycephalosaurus_Reconstruction.jpg", Name = "Pachycephalosaurus", Price = 199.99m, Sku = "00009" },
                        new { ID = 10, Description = "A plated beheamoth with a powerful defensive tail", Image = "https://upload.wikimedia.org/wikipedia/commons/a/a1/Stego.jpg", Name = "Stegosaurus", Price = 199.99m, Sku = "00010" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
